name: js action
description: 'this is a js action'

inputs:
  default_region:
    description: 'this aws region'
    required: true
  ssm_path_name:
    description: 'this SSM path name'
    required: true
  env_name:
    description: 'this env name'
    required: true
  cd_parameters:
    description: 'target SSM Parameters for cd'
    required: false
  parameters:
    description: 'target SSM Parameters'
    required: false

outputs:
  ssm_parameters:
    description: 'ssm_parameters'

runs:
  using: 'node12'
  main: 'index.js'
