name: js action
description: 'this is a js action'

inputs:
  ssm_path_name:
    description: 'ssm_path_name'
    required: true
  env:
    description: 'env'
    required: true
  sample_input_args:
    description: 'sample_input_args'
    required: true

outputs:
  ssm_parameters:
    description: 'ssm_parameters'

runs:
  using: 'node12'
  main: 'index.js'
