name: shell action
description: 'this is a shell action'

inputs:
  sample_input_args:
    description: 'sample_input_args'
    required: true

outputs:
  ssm_parameters:
    description: 'ssm_parameters'

runs:
  using: 'docker'
  image: 'Dockerfile'
