name: get repositroy secret

on:
  push:
    paths: .github/workflows/get_repository_secret.yml

jobs:
  job1:
    name: get repository secret
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Get Secret
        env:
          SAMPLE_REPOSITORY_SECRET: ${{ secrets.SAMPLE_REPOSITORY_SECRET }}　
        run: |
          echo "${SAMPLE_REPOSITORY_SECRET}"
