name: get ssm parameters actions

on:
  push:
    paths:
      - .github/workflows/get_ssm_parameters.yml
      - .github/actions/get_ssm_parameters_action/*

jobs:
  job1:
    name: js actions
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get time for js start
        run: echo "js_start"; echo `date "+%Y-%m-%d %H:%M:%S"`

      - name: Run npm install for actions
        run: |
          cd .github/actions/get_ssm_parameters_action/js_action
          npm install

      - name: Run js action
        id: js-action
        uses: ./.github/actions/get_ssm_parameters_action/js_action
        with:
          sample_input_args: |-
            sample_input1
            sample_input2

      - name: Get js action Output
        id: get-output
        env:
          SAMPLE_OUTPUT_ARGS: ${{ steps.js-action.outputs.sample_output_args }}
        run: |
          TEST_VALUE1="$(jq '.TEST_VALUE1' <(echo "${SAMPLE_OUTPUT_ARGS}"))"
          TEST_VALUE2="$(jq '.TEST_VALUE2' <(echo "${SAMPLE_OUTPUT_ARGS}"))"
          echo "${TEST_VALUE1}"
          echo "${TEST_VALUE2}"

      - name: get time for js end
        run: echo "js_end"; echo `date "+%Y-%m-%d %H:%M:%S"`
