name: pull request merge trigger

on:
  pull_request:
    branches: main
    types: [closed]
  push:
    paths: .github/workflows/pull_request_merge_trigger.yml

jobs:
  job1:
    name: pull request merge trigger
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    if: ${{ github.event.pull_request.merged == true }}

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: run echo
        run: echo "pull request merge trigger"
