name: python actions

on:
  push:
    paths:
      - .github/workflows/python_actions.yml
      - .github/actions/python_action/*

jobs:
  job1:
    name: python actions
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run python action
        id: python-action
        uses: ./.github/actions/python_action
        with:
          sample_input: sample_input
      
      - name: Get shell action Output
        id: get-output
        env:
          SAMPLE_OUTPUT: ${{ steps.python-action.outputs.sample_output }}
        run: |
          echo "${SAMPLE_OUTPUT}"
