name: shell actions

on:
  push:
    paths:
      - .github/workflows/shell_actions.yml
      - .github/actions/shell_action/*

jobs:
  job1:
    name: shell actions
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run shell action
        id: shell-action
        uses: ./.github/actions/shell_action
        with:
          sample_input: sample_input
      
      - name: Get shell action Output
        id: get-output
        env:
          SAMPLE_OUTPUT: ${{ steps.shell-action.outputs.sample_output }}
        run: |
          echo "${SAMPLE_OUTPUT}"
