name: workflow dispatch trigger

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYYmmdd (ex. 19910101, "default" => 実行当日)'
        required: true
        default: default

jobs:
  job1:
    name: workflow dispatch trigger
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: add input to env
        run: |
          # input="${{ github.event.inputs.date }}"
          input="default"
          if [ "$input" == "default" ]; then
            input=$(export TZ="Asia/Tokyo" && date +'%Y%m%d')
          fi

          if [[ ! $input =~ ^[0-9]{8}$ ]]; then
            echo "Error: date is not [YYYYmmdd HHMMSS] format"
            exit 1
          fi

          echo "date=${input}" >> "$GITHUB_ENV"

      - name: run echo
        run: echo $date && echo "workflow dispatch trigger"
