name: workflow dispatch trigger

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYYmmddHHMMSS (ex. 19910101123456)'
        required: true
        default: $(export TZ="Asia/Tokyo" && date +'%Y%m%d%H%M%S')

jobs:
  job1:
    name: workflow dispatch trigger
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: validate input
        run: |
          # input="${{ github.event.inputs.date }}"
          input=12345
          pattern="[0-9]{4}"
          if ! [[ $input =~ $pattern ]]; then
            echo "Error: date is not [YYYYmmdd HHMMSS] format"
            exit 1
          fi

      - name: run echo
        run: echo "workflow dispatch trigger"
