name: workflow dispatch trigger

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYYmmdd (ex. 19910101, "default"の場合本日の日付)'
        required: true
        default: default

jobs:
  job1:
    name: workflow dispatch trigger
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: validate input
        run: |
          # input="${{ github.event.inputs.date }}"
          input=default
          if [ "$input" == "default" ]; then
            input=$(export TZ="Asia/Tokyo" && date +'%Y%m%d')
          fi

          echo $input

          if [[ ! $input =~ ^[0-9]{8}$ ]]; then
            echo "Error: date is not [YYYYmmdd HHMMSS] format"
            exit 1
          fi

      - name: run echo
        run: echo "workflow dispatch trigger"
